"use client";
import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import MainButton from "./components/buttons/MainButton";
import LoginButton from "./components/buttons/LoginButton";
import RegisterButton from "./components/buttons/RegisterButton";

export default function register() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <header className={styles.header}>
        <MainButton text="About" href="/about" />
      </header>
      <main className={styles.main}>
        <div className={styles.mainPic}>
          <Image
            src={"/home.jpg"}
            height={586}
            width={879}
            alt="Connect with other devs"
          />
        </div>
        <div className={styles.cardContainer}>
          <div className={styles.card}>
            <LoginButton />
          </div>
          <div className={styles.card}>
            <RegisterButton />
          </div>
        </div>
      </main>
    </>
  );
}
