import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import MainButton from "@components/pages/components/buttons/MainButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <MainButton text="About" href="/about" />
      </header>
      <main className={styles.main}>
        <div className={styles.mainPic}>
          <Image
            src={"/home.jpg"}
            height={586}
            width={879}
            alt="Connect with other devs"
          />
        </div>
        <div className={styles.cardContainer}>
          <div className={styles.card}></div>
        </div>
      </main>
    </>
  );
}
